version: "3.5"

x-environment:
  &default-back-environment
  SECRET_KEY: "12345"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "invoice"
  POSTGRES_USER: "invoice"
  POSTGRES_PASSWORD: "invoice"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
#  KAVENEGAR_API_KEY:
#  KAVENEGAR_SENDER:
#  DEFAULT_FROM_EMAIL:
#  EMAIL_USE_TLS:
#  EMAIL_USE_SSL:
#  EMAIL_HOST:
#  EMAIL_PORT:
#  EMAIL_HOST_USER:
#  EMAIL_HOST_PASSWORD:
#  BAHAMTA_API_KEY:
#  DOMAIN_WITH_SCHEME:

x-volumes:
  &default-back-volumes
  - invoice-static-data:/app/static
  - invoice-media-data:/app/media

services:
  db:
    image: postgres:alpine
    environment:
      *default-back-environment
    restart: always
    volumes:
      - invoice-db-data:/var/lib/postgresql/data
    networks:
      - invoice
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      *default-back-environment
    restart: always
    volumes:
      *default-back-volumes
    networks:
      - invoice
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - invoice-static-data:/app/static
      - invoice-media-data:/app/media
    restart: always
    networks:
      - invoice
    depends_on:
      - db
      - web

volumes:
  invoice-static-data:
  invoice-media-data:
  invoice-db-data:

networks:
  invoice: