# Generated by Django 3.1.5 on 2022-01-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='customer.customer', verbose_name='Customer'),
        ),
    ]
