# Generated by Django 3.1.5 on 2022-02-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('invoice', '0003_auto_20220214_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencytype',
            options={'ordering': ('name',), 'verbose_name': 'Currency type', 'verbose_name_plural': 'Currency types'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.currencytype', verbose_name='Currency'),
        ),
    ]
