# Generated by Django 3.1.5 on 2021-01-25 20:55

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(blank=True, default=False, verbose_name='Payment status')),
                ('payment_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Payment number')),
                ('payment_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Payment time')),
                ('payment_gateway_response', models.JSONField(blank=True, null=True, verbose_name='Payment gateway response')),
                ('insert_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Insert time')),
                ('payment_url', models.URLField(max_length=2048, null=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice')),
            ],
        ),
    ]
