# Generated by Django 3.1.5 on 2021-01-25 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.PositiveBigIntegerField(default=invoice.models.id_generator, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=256, verbose_name='Customer name')),
                ('invoice_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Invoice number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('09\\d{9}')], verbose_name='Mobile')),
                ('date', django_jalali.db.models.jDateTimeField(verbose_name='Date')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('discount_type', models.BooleanField(choices=[(True, 'Percent'), (False, 'Fix')], default=False, verbose_name='Discount type')),
                ('tax', models.FloatField(default=0, verbose_name='Tax')),
                ('tax_type', models.BooleanField(choices=[(True, 'Percent'), (False, 'Fix')], default=False, verbose_name='Tax type')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('paid_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Paid time')),
                ('send_invoice_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Send invoice time')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ('-date', '-paid_time'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('template', models.FileField(upload_to='invoice')),
            ],
            options={
                'verbose_name': 'Invoice template',
                'verbose_name_plural': 'Invoice templates',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Type')),
                ('cost', models.PositiveBigIntegerField(default=0, verbose_name='Price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Invoice field',
                'verbose_name_plural': 'Invoice fields',
                'ordering': ('invoice', 'title'),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoicetemplate', verbose_name='Invoice template'),
        ),
    ]
